In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

In [17]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


NumPy 数组提供了 ndim 属性，该属性返回一个整数，该整数会告诉我们数组有多少维。

In [3]:
a1 = np.array(61)
a2 = np.array([1,2,3,4,5,6])
a3 = np.array([[1,2,3],[4,5,6]])
a4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a1.ndim)
print(a3)
print(a3.ndim)

0
[[1 2 3]
 [4 5 6]]
2


In [6]:
print(a2[1],a2[2])
print(a2[1] + a2[2])
print(a3[0,1])

2 3
5
2


# 裁切数组
python 中裁切的意思是将元素从一个给定的索引带到另一个给定的索引。

我们像这样传递切片而不是索引：[start：end]。

我们还可以定义步长，如下所示：[start：end：step]。

如果我们不传递 start，则将其视为 0。

如果我们不传递 end，则视为该维度内数组的长度。

如果我们不传递 step，则视为 1。

In [14]:
print(a2)
print(len(a2))
print(a2[1:3])
print(a2[3:6])
print(a2[1:5:2])

[1 2 3 4 5 6]
6
[2 3]
[4 5 6]
[2 4]
(2, 3)


# 数组形状 NumPy 数组有一个名为 shape 的属性，该属性返回一个元组，每个索引具有相应元素的数量。

In [16]:
print(a3.shape)

(2, 3)


# 副本和视图之间的区别
副本和数组视图之间的主要区别在于副本是一个新数组，而这个视图只是原始数组的视图。

每个 NumPy 数组都有一个属性 base，如果该数组拥有数据，则这个 base 属性返回 None。

否则，base 属性将引用原始对象。

In [15]:
x = a2.view()
print(x.base)
y = a2.copy()
print(y.base)

[1 2 3 4 5 6]
None


NumPy 数组重塑

In [19]:
a4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = a4.reshape(4, 3)

print(newarr)
print(newarr.shape)
print(newarr.base)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
print(a3.shape,a3.ndim)
for item in a3:
    print(item)
    for i in item:
        print(i)

print("-----------------------")



(2, 3) 2
[1 2 3]
1
2
3
[4 5 6]
4
5
6
-----------------------


In [23]:
for item in np.nditer(a3):
    print(item)

1
2
3
4
5
6


In [27]:
a6 = np.concatenate((arr,a2))
print(a6)

[1 2 3 4 5 1 2 3 4 5 6]
